#!/usr/bin/env bash

# installing nginx

apt-get update

apt-get install -y nginx

# Configure Nginx
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    location / {
        return 200 "Hello World!\n";
    }
}
EOF

service nginx restart
