#!/usr/bin/env bash
# installing nginx

apt-get update

apt-get install -y nginx

# Configure Nginx
mkdir /var/www/mysite
mkdir /var/www/mysite/html
touch /var/www/mysite/html/index.html
echo "Hello World!" > /var/www/mysite/html/index.html
chmod 644 /var/www/mysite/html/index.html
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/mysite/html;
    index index.html index.htm;

    location / {
    }
}
EOF

service nginx restart
