#!/usr/bin/env bash

# installing nginx

apt-get update

apt-get install -y nginx

# Configure Nginx
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    location /not_found{
        return 404 "Ceci n'est pas une page\n";
    }
}
EOF

service nginx restart
