#!/usr/bin/env bash
# add a customer header with value of host name to the header file

sudo sed -i '/^http {/a \    add_header X-Served-By $hostname;' /etc/nginx/nginx.conf

sudo service nginx restart
