#!/usr/bin/env bash
# installing HAproxy load balancer software

sudo apt-get update -y
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt-get install haproxy=2.8.\* -y

sudo service haproxy start

# Configuring HAproxy to 
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sed -i '$ a frontend myfrontend\n\tbind 0.0.0.0:80\n\tdefault_backend myservers\n\nbackend myservers\n\tserver webserver1 54.237.68.227:80 check\n\tserver webserver2 52.3.247.66:80 check\n' /etc/haproxy/haproxy.cfg

sudo service haproxy restart
