#!/usr/bin/env bash
# Create a file and save is pid and then perform other operation
touch /var/run/myscript.pid
pidof /var/run/myscript.pid > /var/run/myscript.pid
for ((i=0; ;i++))
do
	echo "To infinity and beyond"
	if ((SIGTERM))
	then
		echo "I hate the kill command"
	elif ((SIGINT))
	then
		echo "Y U no love me?!"
	fi
done
rm -rf /var/run/myscript.pid
