#!/usr/bin/env bash
# handle SIGTERM signal
trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "exit" SIGQUIT SIGTERM
for ((i=0; ; i++))
do
	echo "To infinity and beyond"
	sleep 2
done
