#!/usr/bin/env bash
# lops 10x, prints "bad luck" for 4th loop on the 9x print
# prints "good luck" for 8th loop
#prints "Best school" for other iteration
n=1
while ((n <= 10))
do
	if ((n == 4))
	then
		echo "bad luck"
	elif ((n == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((n++))
done
