#!/usr/bin/env bash
# gives information about a file named "school"

File=school
if test -e "$File"
then
	echo "school file exists"
	if ! test -s "$File"
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if test -f "$File"
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
