#!/usr/bin/env bash
# run software as another user
sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Stop Nginx if it is currently running
sudo service nginx stop

# Replace "user root;" with "user nginx;" in the Nginx configuration file
sed -i '1i\# running nginx under nginx user' /etc/nginx/nginx.conf
sed -i '2i\user nginx;' /etc/nginx/nginx.conf

# Start Nginx to run as the nginx user
sudo service nginx start
